language: python
script:
  - tox
before_install:
  - openssl version
cache:
  directories:
  - ${HOME}/.cache
install:
  - pip install tox==2.1.1 tox-travis
  - if [[ "${TOXENV}" == "gae" && ! -d ${GAE_PYTHONPATH} ]]; then
      python _travis/fetch_gae_sdk.py ;
    fi
notifications:
  email: false
env:
  global:
    - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
    - PYTHONWARNINGS=always::DeprecationWarning
matrix:
  include:
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-cryptography

sudo: false
